# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &snd_git 75035FA99C09E99336461218A8C13B19E24AF69E
  - &thinkpad age1y3exu23pvels7rkwwq4ws5mmldudgnu4p9nruyfc3h6vayhdwc2sn7seaq
  - &desktop age124xlpxdfwprf0raqecygltknswn6fgqm2nf65l5q00xc35vwnqcqkn4uh0
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
    - pgp:
      - *snd_git
      age:
      - *thinkpad
      - *desktop
  - path_regex: git-secrets\.json$
    key_groups:
      - pgp:
        - *snd_git
